# Generated by Django 3.1.1 on 2020-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storeitems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('item_price', models.IntegerField()),
                ('item_qty', models.IntegerField()),
            ],
        ),
    ]
